/* Gramatica.java */
/* Generated By:JavaCC: Do not edit this line. Gramatica.java */
import java.util.*;
import java.io.*;

class Gramatica implements GramaticaConstants {

    static ArrayList<String> nombreVariable = new ArrayList<String>();
    static ArrayList<String> tipoDato = new ArrayList<String>();
    static ArrayList<String> valorAlmacenado = new ArrayList<String>();
    static ArrayList<String> erroresLexicos = new ArrayList<String>();
    static ArrayList<String> erroresSintacticos = new ArrayList<String>();
    static ArrayList<String> erroresSemanticos = new ArrayList<String>();
    static ArrayList<String> colaOperacion = new ArrayList<String>();

    static String nombreV ="";
    static String tipoD ="";
    static String valorV="nulo";
    static boolean ident = false;
    static boolean decAritmetica = false;
    static boolean asignacion_a = false;

    public static void main(String[] args )  throws FileNotFoundException {

    System.out.println("Ingresa el nombre del archivo que quieres analizar");
    Scanner entrada = new Scanner (System.in);
    String str = entrada.next();

    str+= ".txt";
    FileReader file = new FileReader(str);
    BufferedReader buffer = new BufferedReader (file);
    Gramatica analizador = new Gramatica (buffer);
        inicio(str,file,buffer,analizador);
    }
    static void inicio(String str,FileReader file, BufferedReader buffer,Gramatica analizador)throws FileNotFoundException {


    try{

        analizador.Programa();




    }catch (ParseException e) {

        Token t;


         do {
       t = getNextToken();
       if(t.kind== EOF)break;

         } while (t!=null && t.kind != EOF  );
    }

    if(erroresLexicos.isEmpty() && erroresSintacticos.isEmpty() && erroresSemanticos.isEmpty()){

    System.out.println("Ejecucion finalizada sin errores");

    }


    else{

        int ntotal = erroresLexicos.size()+erroresSemanticos.size()+erroresSintacticos.size();

       if(ntotal==1)    System.out.println("\u005cnEjecucion finalizada con "+ntotal+" error " );
        else    System.out.println("\u005cnEjecucion finalizada con "+ntotal+" errores " );

        if(!erroresLexicos.isEmpty()){

        System.out.println("");
        if(erroresLexicos.size()==1) System.out.println("Se ha encontrado " +erroresLexicos.size() + " error lexico");


        else System.out.println("Se han encontrado " +erroresLexicos.size() + " errores lexicos");


            for (String impresion: erroresLexicos) {
            System.out.println(impresion);

                }
            }

         if(!erroresSintacticos.isEmpty()){

        System.out.println("");
        if(erroresSintacticos.size()==1) System.out.println("Se ha encontrado " +erroresSintacticos.size() + " error sintactico");


        else System.out.println("Se han encontrado " +erroresSintacticos.size() + " errores sintacticos");

            System.out.println("");

            for (String impresion: erroresSintacticos) {
            System.out.println(impresion);

                }
            }

        if(!erroresSemanticos.isEmpty()){

        System.out.println("");
        if(erroresSemanticos.size()==1) System.out.println("Se ha encontrado " +erroresSemanticos.size() + " error semantico");


            else System.out.println("Se han encontrado " +erroresSemanticos.size() + " errores semanticos");

            System.out.println("");

            for (String impresion: erroresSemanticos) {
            System.out.println(impresion);

                }
            }


        }


    }






static void errorData(Token currentTokenVal,
                        int[][] expectedTokenSequencesVal,
                        String[] tokenImageVal){
    String eol = System.getProperty("line.separator", "\u005cn");
    Token currentToken = currentTokenVal;
    int [][] expectedTokenSequences = expectedTokenSequencesVal;
    String[] tokenImage = tokenImageVal;
    StringBuffer expected = new StringBuffer();
    int maxSize = 0;
    for (int i = 0; i < expectedTokenSequences.length; i++) {
      if (maxSize < expectedTokenSequences[i].length) {
        maxSize = expectedTokenSequences[i].length;
      }
      for (int j = 0; j < expectedTokenSequences[i].length; j++) {
        expected.append(tokenImage[expectedTokenSequences[i][j]]).append(' ');
      }
      if (expectedTokenSequences[i][expectedTokenSequences[i].length - 1] != 0) {
        expected.append("...");
      }
      expected.append(eol).append("    ");
    }


    if(currentToken.next.kind == 0)return;

    String retval = "";


    retval+="Error Sintactico, ";
    retval += "Se ha encontrado \u005c"";
    Token tok = currentToken.next;
    for (int i = 0; i < maxSize; i++) {
      if (i != 0) retval += " ";
      if (tok.kind == 0) {
        retval += tokenImage[0];
        break;
      }
      retval += " " + tokenImage[tok.kind];
      retval += " \u005c"";
      retval += add_escapes(tok.image);
      retval += " \u005c"";
      tok = tok.next;
    }
    retval += "\u005c" en la linea " + currentToken.next.beginLine + ", columna " + currentToken.next.beginColumn;
    retval += "." + eol;
    if (expectedTokenSequences.length == 1) {
      retval += "Se esperaba:" + eol + "    ";
    } else {
      retval += "Se esperaba:" + eol + "    ";
    }
    retval += expected.toString();

    erroresSintacticos.add(retval);
    }





    static String add_escapes(String str) {
      StringBuffer retval = new StringBuffer();
      char ch;
      for (int i = 0; i < str.length(); i++) {
        switch (str.charAt(i))
        {
           case 0 :
              continue;
           case '\u005cb':
              retval.append("\u005c\u005cb");
              continue;
           case '\u005ct':
              retval.append("\u005c\u005ct");
              continue;
           case '\u005cn':
              retval.append("\u005c\u005cn");
              continue;
           case '\u005cf':
              retval.append("\u005c\u005cf");
              continue;
           case '\u005cr':
              retval.append("\u005c\u005cr");
              continue;
           case '\u005c"':
              retval.append("\u005c\u005c\u005c"");
              continue;
           case '\u005c'':
              retval.append("\u005c\u005c\u005c'");
              continue;
           case '\u005c\u005c':
              retval.append("\u005c\u005c\u005c\u005c");
              continue;
           default:
              if ((ch = str.charAt(i)) < 0x20 || ch > 0x7e) {
                 String s = "0000" + Integer.toString(ch, 16);
                 retval.append("\u005c\u005cu" + s.substring(s.length() - 4, s.length()));
              } else {
                 retval.append(ch);
              }
              continue;
        }
      }
      return retval.toString();

    }

//----------------------------------------FIN DECLARACION TOKENS -------------------------------------------------------
//----------------------------------------INICIO DECLARACION GRAMATICAS -------------------------------------------------------

//----------------------------------------PROGRAMA PRINCIPAL -------------------------------------------------------
  static final public     void Programa() throws ParseException {
    jj_consume_token(MAIN);
    jj_consume_token(PARI);
    jj_consume_token(PARD);
    jj_consume_token(LLAVEI);
    Bloque();
    jj_consume_token(LLAVED);
    jj_consume_token(0);
  }

//----------------------------------------BLOQUE DE SENTENCIAS -------------------------------------------------------
  static final public     void Bloque() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WRITE:
      case READ:
      case IF:
      case BREAK:
      case FOR:
      case WHILE:
      case ASIGN:
      case ASIGN_A:
      case DECLARATE:
      case DECLARATE_A:
      case ICR:
      case DCR:
      case ERRORES:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      sentencia();
    }
  }

//----------------------------------------SENTENCIAS -------------------------------------------------------
  static final public     void sentencia() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WRITE:{
      imprimir();
      break;
      }
    case ERRORES:{
      errorLexico();
      break;
      }
    case DECLARATE:{
      declaraciones();
      break;
      }
    case ASIGN:{
      asignaciones();
      break;
      }
    case ICR:
    case DCR:{
      incrementoDecremento();
      break;
      }
    case IF:{
      condicionalIf();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      if (jj_2_1(2)) {
        cicloFor();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BREAK:{
          jj_consume_token(BREAK);
          delimiter();
          break;
          }
        case WHILE:{
          cicloWhile();
          break;
          }
        case READ:{
          leer();
          break;
          }
        case DECLARATE_A:{
          declaracionAritmetica();
          break;
          }
        case ASIGN_A:{
          asignacionAritmetica();
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

//---------------------------------------- IMPRIMIR -------------------------------------------------------
  static final public     void imprimir() throws ParseException {
    jj_consume_token(WRITE);
    pari();
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFICADOR:{
        jj_consume_token(IDENTIFICADOR);
errorSemanticoImprimir();
        break;
        }
      case NUMERO:{
        jj_consume_token(NUMERO);
        break;
        }
      case DECIMAL:{
        jj_consume_token(DECIMAL);
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
        break;
        }
      case NULL:{
        jj_consume_token(NULL);
        break;
        }
      case CADENA:{
        jj_consume_token(CADENA);
        break;
        }
      case CHAR:{
        jj_consume_token(CHAR);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IDENTIFICADOR && t.kind != NUMERO &&
               t.kind != DECIMAL  && t.kind != TRUE &&  t.kind != FALSE &&
               t.kind != CADENA && t.kind != CHAR &&  t!=null && t.kind != EOF );
    }
    pard();
    delimiter();
  }

//---------------------------------------- DECLARACIONES -------------------------------------------------------
  static final public     void declaraciones() throws ParseException {
    jj_consume_token(DECLARATE);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:{
        jj_consume_token(INT);
        break;
        }
      case CARACTER:{
        jj_consume_token(CARACTER);
        break;
        }
      case FLOAT:{
        jj_consume_token(FLOAT);
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
        break;
        }
      case BOOL:{
        jj_consume_token(BOOL);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
guardarTipoDato();
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != INT && t.kind != CARACTER &&
               t.kind != FLOAT && t.kind != STRING &&  t.kind != BOOL &&
               t!=null && t.kind != EOF );
    }
    identificador();
guardarNombreV();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:{
      igual();
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          jj_consume_token(IDENTIFICADOR);
ident = true;
          break;
          }
        case NUMERO:{
          jj_consume_token(NUMERO);
          break;
          }
        case DECIMAL:{
          jj_consume_token(DECIMAL);
          break;
          }
        case TRUE:{
          jj_consume_token(TRUE);
          break;
          }
        case FALSE:{
          jj_consume_token(FALSE);
          break;
          }
        case NULL:{
          jj_consume_token(NULL);
          break;
          }
        case CADENA:{
          jj_consume_token(CADENA);
          break;
          }
        case CHAR:{
          jj_consume_token(CHAR);
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
guardarValorV();
      } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IDENTIFICADOR && t.kind != NUMERO &&
               t.kind != DECIMAL  && t.kind != TRUE &&  t.kind != FALSE &&
               t.kind != CADENA && t.kind != CHAR &&  t!=null && t.kind != EOF );
      }
      delimiter();
declarar();
      break;
      }
    case DELIMITER:{
      delimiter();
declarar();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//---------------------------------------- DECLARACIONES CON OPERACIONES ARITMETICAS -------------------------------------------------------
  static final public     void declaracionAritmetica() throws ParseException {
    jj_consume_token(DECLARATE_A);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:{
        jj_consume_token(INT);
        break;
        }
      case CARACTER:{
        jj_consume_token(CARACTER);
        break;
        }
      case FLOAT:{
        jj_consume_token(FLOAT);
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
        break;
        }
      case BOOL:{
        jj_consume_token(BOOL);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
guardarTipoDato();
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != INT && t.kind != CARACTER &&
               t.kind != FLOAT && t.kind != STRING &&  t.kind != BOOL &&
               t!=null && t.kind != EOF );
    }
    identificador();
guardarNombreV();
    igual();
    operacion();
    delimiter();
decAritmetica=true;declarar();
  }

//----------------------------------------OPERACIONES ARITMETICAS-------------------------------------------------------
  static final public     void operacion() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMERO:{
        jj_consume_token(NUMERO);
        break;
        }
      case IDENTIFICADOR:{
        jj_consume_token(IDENTIFICADOR);
        break;
        }
      case DECIMAL:{
        jj_consume_token(DECIMAL);
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
guardarColaOperacion();
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != NUMERO && t.kind != IDENTIFICADOR &&
               t.kind != DECIMAL && t!=null && t.kind != EOF );
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:
      case MENOS:
      case MULTIPLICAR:
      case DIVIDIR:
      case MODULO:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_2;
      }
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MAS:{
          jj_consume_token(MAS);
          break;
          }
        case MENOS:{
          jj_consume_token(MENOS);
          break;
          }
        case MULTIPLICAR:{
          jj_consume_token(MULTIPLICAR);
          break;
          }
        case DIVIDIR:{
          jj_consume_token(DIVIDIR);
          break;
          }
        case MODULO:{
          jj_consume_token(MODULO);
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
guardarColaOperacion();
      } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != MAS && t.kind != MENOS &&
               t.kind != MULTIPLICAR && t.kind != DIVIDIR && t.kind != MODULO && t!=null && t.kind != EOF );
      }
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NUMERO:{
          jj_consume_token(NUMERO);
          break;
          }
        case IDENTIFICADOR:{
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case DECIMAL:{
          jj_consume_token(DECIMAL);
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
guardarColaOperacion();
      } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != NUMERO && t.kind != IDENTIFICADOR &&
               t.kind != DECIMAL && t!=null && t.kind != EOF );
      }
    }
  }

//---------------------------------------- ASIGNACIONES CON OPERACIONES ARITMETICAS -------------------------------------------------------
  static final public     void asignacionAritmetica() throws ParseException {
    jj_consume_token(ASIGN_A);
    identificador();
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL:{
        jj_consume_token(IGUAL);
        break;
        }
      case SUMAIGUAL:{
        jj_consume_token(SUMAIGUAL);
        break;
        }
      case RESTAIGUAL:{
        jj_consume_token(RESTAIGUAL);
        break;
        }
      case MULTIGUAL:{
        jj_consume_token(MULTIGUAL);
        break;
        }
      case DIVIDIRIGUAL:{
        jj_consume_token(DIVIDIRIGUAL);
        break;
        }
      case MODULOIGUAL:{
        jj_consume_token(MODULOIGUAL);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IGUAL && t.kind != SUMAIGUAL &&
               t.kind != RESTAIGUAL && t.kind != MULTIGUAL && t.kind != DIVIDIRIGUAL &&
               t.kind != MODULOIGUAL && t!=null && t.kind != EOF );
    }
    operacion();
    delimiter();
  }

//----------------------------------------GRAMATICAS INCREMENTO O DECREMENTO -------------------------------------------------------
  static final public     void incrementoDecremento() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ICR:{
      jj_consume_token(ICR);
      break;
      }
    case DCR:{
      jj_consume_token(DCR);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    identificador();
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:{
        jj_consume_token(MAS);
        jj_consume_token(MAS);
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        jj_consume_token(MENOS);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != MAS && t.kind != MENOS &&
              t!=null && t.kind != EOF );
    }
    delimiter();
  }

//----------------------------------------ASIGNACIONES NORMALES -------------------------------------------------------
  static final public     void asignaciones() throws ParseException {
    jj_consume_token(ASIGN);
    identificador();
guardarNombreV();
    igual();
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFICADOR:{
        jj_consume_token(IDENTIFICADOR);
ident = true;
        break;
        }
      case NUMERO:{
        jj_consume_token(NUMERO);
        break;
        }
      case DECIMAL:{
        jj_consume_token(DECIMAL);
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
        break;
        }
      case NULL:{
        jj_consume_token(NULL);
        break;
        }
      case CADENA:{
        jj_consume_token(CADENA);
        break;
        }
      case CHAR:{
        jj_consume_token(CHAR);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
guardarValorV();
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IDENTIFICADOR && t.kind != NUMERO && t.kind != DECIMAL &&
              t.kind != TRUE && t.kind != FALSE && t.kind != CADENA &&
            t.kind != CADENA && t.kind != CHAR && t != null && t.kind != EOF );
    }
    delimiter();
asignar();
  }

//----------------------------------------COMPARACION LOGICA -------------------------------------------------------
  static final public     void comparacionLogica() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NEGACION:{
        jj_consume_token(NEGACION);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case NUMERO:{
          jj_consume_token(NUMERO);
          break;
          }
        case DECIMAL:{
          jj_consume_token(DECIMAL);
          break;
          }
        case CADENA:{
          jj_consume_token(CADENA);
          break;
          }
        case CHAR:{
          jj_consume_token(CHAR);
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case IDENTIFICADOR:{
        jj_consume_token(IDENTIFICADOR);
        break;
        }
      case NUMERO:{
        jj_consume_token(NUMERO);
        break;
        }
      case DECIMAL:{
        jj_consume_token(DECIMAL);
        break;
        }
      case CADENA:{
        jj_consume_token(CADENA);
        break;
        }
      case CHAR:{
        jj_consume_token(CHAR);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IDENTIFICADOR && t.kind != NUMERO && t.kind != DECIMAL &&
              t.kind != NEGACION && t.kind != CADENA && t.kind != CHAR && t != null && t.kind != EOF );
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUALDAD:
      case MAYOR:
      case MAYORI:
      case MENOR:
      case MENORI:
      case DIFERENCIA:
      case AND:
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_3;
      }
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IGUALDAD:{
          jj_consume_token(IGUALDAD);
          break;
          }
        case MAYOR:{
          jj_consume_token(MAYOR);
          break;
          }
        case MAYORI:{
          jj_consume_token(MAYORI);
          break;
          }
        case MENOR:{
          jj_consume_token(MENOR);
          break;
          }
        case MENORI:{
          jj_consume_token(MENORI);
          break;
          }
        case DIFERENCIA:{
          jj_consume_token(DIFERENCIA);
          break;
          }
        case AND:{
          jj_consume_token(AND);
          break;
          }
        case OR:{
          jj_consume_token(OR);
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IGUALDAD && t.kind != MAYORI && t.kind != MENOR &&
              t.kind != MENORI && t.kind != DIFERENCIA && t.kind != AND &&
              t.kind != OR && t != null && t.kind != EOF );
      }
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEGACION:{
          jj_consume_token(NEGACION);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case IDENTIFICADOR:{
            jj_consume_token(IDENTIFICADOR);
            break;
            }
          case NUMERO:{
            jj_consume_token(NUMERO);
            break;
            }
          case DECIMAL:{
            jj_consume_token(DECIMAL);
            break;
            }
          case CADENA:{
            jj_consume_token(CADENA);
            break;
            }
          case CHAR:{
            jj_consume_token(CHAR);
            break;
            }
          default:
            jj_la1[20] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        case IDENTIFICADOR:{
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case NUMERO:{
          jj_consume_token(NUMERO);
          break;
          }
        case DECIMAL:{
          jj_consume_token(DECIMAL);
          break;
          }
        case CADENA:{
          jj_consume_token(CADENA);
          break;
          }
        case CHAR:{
          jj_consume_token(CHAR);
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != IDENTIFICADOR && t.kind != NUMERO && t.kind != DECIMAL &&
              t.kind != NEGACION && t.kind != CADENA && t.kind != CHAR && t != null && t.kind != EOF );
      }
    }
  }

//----------------------------------------ESTRUCTURA CONDICIONAL IF -------------------------------------------------------
  static final public     void condicionalIf() throws ParseException {
    jj_consume_token(IF);
    pari();
    comparacionLogica();
    pard();
    llavei();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WRITE:
      case READ:
      case IF:
      case BREAK:
      case FOR:
      case WHILE:
      case ASIGN:
      case ASIGN_A:
      case DECLARATE:
      case DECLARATE_A:
      case ICR:
      case DCR:
      case ERRORES:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_4;
      }
      sentencia();
    }
    llaved();
    label_5:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_5;
      }
      sino();
      si();
      pari();
      comparacionLogica();
      pard();
      llavei();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WRITE:
        case READ:
        case IF:
        case BREAK:
        case FOR:
        case WHILE:
        case ASIGN:
        case ASIGN_A:
        case DECLARATE:
        case DECLARATE_A:
        case ICR:
        case DCR:
        case ERRORES:{
          ;
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          break label_6;
        }
        sentencia();
      }
      llaved();
    }
    label_7:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_7;
      }
      sino();
      llavei();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WRITE:
        case READ:
        case IF:
        case BREAK:
        case FOR:
        case WHILE:
        case ASIGN:
        case ASIGN_A:
        case DECLARATE:
        case DECLARATE_A:
        case ICR:
        case DCR:
        case ERRORES:{
          ;
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          break label_8;
        }
        sentencia();
      }
      llaved();
    }
  }

//---------------------------------------- ESTRUCTURA CICLO FOR -------------------------------------------------------
  static final public     void cicloFor() throws ParseException {
    jj_consume_token(FOR);
    pari();
    identificador();
    igual();
    numero();
    delimiter();
    identificador();
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:{
        jj_consume_token(MENOR);
        break;
        }
      case MAYOR:{
        jj_consume_token(MAYOR);
        break;
        }
      case MENORI:{
        jj_consume_token(MENORI);
        break;
        }
      case MAYORI:{
        jj_consume_token(MAYORI);
        break;
        }
      case IGUALDAD:{
        jj_consume_token(IGUALDAD);
        break;
        }
      case DIFERENCIA:{
        jj_consume_token(DIFERENCIA);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != MENOR && t.kind != MAYOR && t.kind != MENORI &&
              t.kind != MAYORI && t.kind != IGUALDAD  && t.kind != DIFERENCIA && t != null && t.kind != EOF );
    }
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMERO:{
        jj_consume_token(NUMERO);
        break;
        }
      case IDENTIFICADOR:{
        jj_consume_token(IDENTIFICADOR);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != NUMERO && t.kind != IDENTIFICADOR && t != null && t.kind != EOF );
    }
    delimiter();
    identificador();
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:{
        jj_consume_token(MAS);
        jj_consume_token(MAS);
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        jj_consume_token(MENOS);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         }
        while (t.kind != MAS && t.kind != MENOS && t != null && t.kind != EOF );
    }
    pard();
    llavei();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WRITE:
      case READ:
      case IF:
      case BREAK:
      case FOR:
      case WHILE:
      case ASIGN:
      case ASIGN_A:
      case DECLARATE:
      case DECLARATE_A:
      case ICR:
      case DCR:
      case ERRORES:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_9;
      }
      sentencia();
    }
    llaved();
  }

//----------------------------------------ESTRUCTURA CICLO WHILE -------------------------------------------------------
  static final public     void cicloWhile() throws ParseException {
    jj_consume_token(WHILE);
    pari();
    comparacionLogica();
    pard();
    llavei();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WRITE:
      case READ:
      case IF:
      case BREAK:
      case FOR:
      case WHILE:
      case ASIGN:
      case ASIGN_A:
      case DECLARATE:
      case DECLARATE_A:
      case ICR:
      case DCR:
      case ERRORES:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_10;
      }
      sentencia();
    }
    llaved();
  }

//----------------------------------------LEER DATOS DESDE TECLADO -------------------------------------------------------
  static final public     void leer() throws ParseException {
    jj_consume_token(READ);
    pari();
    identificador();
guardarNombreV();
    pard();
    delimiter();
errorSemanticoLeer();
  }

  static final public void delimiter() throws ParseException {
    try {
      jj_consume_token(DELIMITER);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != DELIMITER && t!=null && t.kind != EOF );
    }
  }

  static final public void llavei() throws ParseException {
    try {
      jj_consume_token(LLAVEI);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != LLAVEI && t!=null && t.kind != EOF );
    }
  }

  static final public void llaved() throws ParseException {
    try {
      jj_consume_token(LLAVED);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != LLAVED && t!=null && t.kind != EOF );
    }
  }

  static final public void pari() throws ParseException {
    try {
      jj_consume_token(PARI);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != PARI && t!=null && t.kind != EOF );
    }
  }

  static final public void pard() throws ParseException {
    try {
      jj_consume_token(PARD);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != PARD && t!=null && t.kind != EOF );
    }
  }

  static final public void identificador() throws ParseException {
    try {
      jj_consume_token(IDENTIFICADOR);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != IDENTIFICADOR && t!=null && t.kind != EOF );
    }
  }

  static final public void igual() throws ParseException {
    try {
      jj_consume_token(IGUAL);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != IGUAL && t!=null && t.kind != EOF );
    }
  }

  static final public void negacion() throws ParseException {
    try {
      jj_consume_token(NEGACION);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != NEGACION && t!=null && t.kind != EOF );
    }
  }

  static final public void numero() throws ParseException {
    try {
      jj_consume_token(NUMERO);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != NUMERO && t!=null && t.kind != EOF );
    }
  }

  static final public void decimal() throws ParseException {
    try {
      jj_consume_token(DECIMAL);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != DECIMAL && t!=null && t.kind != EOF );
    }
  }

  static final public void cadena() throws ParseException {
    try {
      jj_consume_token(CADENA);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != CADENA && t!=null && t.kind != EOF );
    }
  }

  static final public void caracter() throws ParseException {
    try {
      jj_consume_token(CHAR);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != CHAR && t!=null && t.kind != EOF );
    }
  }

  static final public void sino() throws ParseException {
    try {
      jj_consume_token(ELSE);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != ELSE && t!=null && t.kind != EOF );
    }
  }

  static final public void si() throws ParseException {
    try {
      jj_consume_token(IF);
    } catch (ParseException e) {
Token t;
        errorData(e.currentToken,e.expectedTokenSequences,e.tokenImage);
        System.out.println("");
         do {
       t = getNextToken();
         } while (t.kind != IF && t!=null && t.kind != EOF );
    }
  }

  static final public void eof() throws ParseException {
    try {
      jj_consume_token(0);
    } catch (ParseException e) {
Token t;

         do {
       t = getNextToken();
         } while ( t!=null );
    }
  }

  static final public void errorLexico() throws ParseException {
    jj_consume_token(ERRORES);
error();
  }

  static public void error() throws ParseException {String errorL ="\u005cnError Lexico \u005c"" + token.image+"\u005c" en la linea "+token.beginLine
    +" columna "+token.beginColumn+"\u005cn";
    erroresLexicos.add(errorL);
    errorL="";
  }

  static public void guardarNombreV() throws ParseException {nombreV=token.image;
  }

  static public void guardarTipoDato() throws ParseException {tipoD=token.image;
  }

  static public void guardarValorV() throws ParseException {valorV=token.image;
  }

  static public boolean isNumeric(String cadena) throws ParseException {boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
  }

  static public boolean isFloat(String cadena) throws ParseException {boolean resultado;

        try {
            Float.parseFloat(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
  }

  static public boolean busquedaV(String str) throws ParseException {if(nombreVariable.isEmpty())return false;

        else{

        for(String buscar : nombreVariable){

        if(buscar.equals(str))return true;

        }

        }

        return false;
  }

  static public void errorSemanticoImprimir() throws ParseException {int pos = nombreVariable.indexOf(token.image);

    if(pos !=-1){


           if(valorAlmacenado.get(pos).equals("nulo")){

           String errorS = "Error Semantico en la linea " + token.beginLine + " no se ha asignado un valor a la variable";
            erroresSemanticos.add(errorS);

            }

    }

    else{

    String errorS = "Error Semantico en la linea " + token.beginLine + " no se ha declarado la variable";
    erroresSemanticos.add(errorS);

    }
  }

  static public void errorSemanticoLeer() throws ParseException {if(!busquedaV(nombreV)){

            String errorS = "Error Semantico en la linea " + token.beginLine + " la variable que se intenta leer no se ha declarado";
            erroresSemanticos.add(errorS);
            nombreV="";

            }
  }

  static public void guardarColaOperacion() throws ParseException {colaOperacion.add(token.image);
  }

  static public boolean realizarOperacion() throws ParseException {int acc = 1;

        //SI ES UN ENTERO
        if(tipoD.equals("entero")){
        int valor = 0;



        for(String s1 : colaOperacion){

                //SI ES UN OPERADOR
                if(s1.equals("+"))acc=1;
                else if(s1.equals("-"))acc=2;
                else if(s1.equals("*"))acc=3;
                else if(s1.equals("/"))acc=4;

                //SI ES UN OPERANDO
                else if(isNumeric(s1)){

                    if(acc==1)valor+= Integer.parseInt(s1);
                    if(acc==2)valor-= Integer.parseInt(s1);
                    if(acc==3)valor*= Integer.parseInt(s1);
                    if(acc==4)valor/= Integer.parseInt(s1);

                }

                else if(isFloat(s1)){

                        String errorS = "Error Semantico en la linea " + token.beginLine + " los operandos son de tipos distintos";
                        erroresSemanticos.add(errorS);
                        return false;

                        }

                else{
                    // BUSCA SI ES UNA VARIABLE
                    if(busquedaV(s1)){

                        int indice = nombreVariable.indexOf(s1);

                        int x;

                        try{
                           String s2 = valorAlmacenado.get(indice);

                           if(s2.equals("nulo")){
                            String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no se ha inicializado";
                            erroresSemanticos.add(errorS);
                            return false;

                            }

                           x = Integer.parseInt(s2);

                           if(acc==1)valor+= x;
                           if(acc==2)valor-= x;
                           if(acc==3)valor*= x;
                           if(acc==4)valor/= x;


                        }
                        catch(NumberFormatException ex){

                            String errorS = "Error Semantico en la linea " + token.beginLine + " tipos incompatibles";
                            erroresSemanticos.add(errorS);
                            return false;

                        }


                        }
                        //NO SE ENCONTRO LA VARIABLE
                      else{

                            String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no se ha declarado";
                            erroresSemanticos.add(errorS);
                            return false;

                    }

                }



            }

            valorV = Integer.toString(valor);
            return true;

        }
        //SI ES UN FLOTANTE
        else if(tipoD.equals("flotante")){
        float valor = 0;

            for(String s1 : colaOperacion){

                if(s1.equals("+"))acc=1;
                else if(s1.equals("-"))acc=2;
                else if(s1.equals("*"))acc=3;
                else if(s1.equals("/"))acc=4;

                //ES UN OPERANDO
                else if(isFloat(s1)){

                    if(acc==1)valor+= Float.parseFloat(s1);
                    if(acc==2)valor-= Float.parseFloat(s1);
                    if(acc==3)valor*= Float.parseFloat(s1);;
                    if(acc==4)valor/= Float.parseFloat(s1);

                }

                else{
                    // BUSCA SI ES UNA VARIABLE
                    if(busquedaV(s1)){

                        int indice = nombreVariable.indexOf(s1);

                        float x;

                        try{
                           String s2 = valorAlmacenado.get(indice);

                           if(s2.equals("nulo")){
                            String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no se ha inicializado";
                            erroresSemanticos.add(errorS);
                            return false;

                            }

                           x = Float.parseFloat(s2);

                           if(acc==1)valor+= x;
                           if(acc==2)valor-= x;
                           if(acc==3)valor*= x;
                           if(acc==4)valor/= x;


                        }
                        catch(NumberFormatException ex){

                            String errorS = "Error Semantico en la linea " + token.beginLine + " tipos incompatibles";
                            erroresSemanticos.add(errorS);
                            return false;

                        }


                        }
                        //NO SE ENCONTRO LA VARIABLE
                      else{

                            String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no se ha declarado";
                            erroresSemanticos.add(errorS);
                            return false;

                    }

                }


            }

            valorV = Float.toString(valor);
            return true;
         }



        else return false;
  }

  static public void declarar() throws ParseException {//SI SE HACE UNA DECLARACION ARITMETICA
        if(decAritmetica){
            decAritmetica = false;
            if(!realizarOperacion()){
            nombreV="";
            tipoD="";
            valorV="nulo";
            return;
            }
        }

        //SI LO ASIGNADO A LA VARIABLE ES UN IDENTIFICADOR
        if(ident){
            ident = false;

                //BUSCAMOS SI LA VARIABLE YA FUE DEFINIDA

                if(busquedaV(valorV)){
                    //SI LA ENCONTRO Y PROCEDEMOS A VERIFICAR QUE SEAN DEL MISMO TIPO

                       int indiceV  = nombreVariable.indexOf(valorV);


                       if(tipoDato.get(indiceV).equals(tipoD)){
                            //VERIFICA QUE LA VARIABLE ESTE INICIALIZADA


                                if(!valorAlmacenado.get(indiceV).equals("nulo")){

                                //METEMOS EL VALOR A LA VARIABLE CORRESPONDIENTE

                                    valorV = valorAlmacenado.get(indiceV);
                                }

                                else{

                                //NO SE HA INICIALIZADO LA VARIABLE

                                    String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no se ha inicializado";
                                    erroresSemanticos.add(errorS);
                                    errorS="";
                                    nombreV="";
                                    tipoD="";
                                    valorV="nulo";
                                    return;

                                }


                        }

                        //NO SON DEL MISMO TIPO
                        else{
                          String errorS = "Error Semantico en la linea " + token.beginLine + " la variables no son del mismo tipo";
                          erroresSemanticos.add(errorS);
                          errorS="";
                          nombreV="";
                          tipoD="";
                          valorV="nulo";
                          return;
                          }


                    }

                //EN CASO DE QUE LA VARIABLE NO SE HA DEFINIDO
                else{

                String errorS = "Error Semantico en la linea " + token.beginLine + " la variable que se busca asignar no ha sido definida";
                erroresSemanticos.add(errorS);
                errorS="";
                nombreV="";
                tipoD="";
                valorV="nulo";
                return;
                }

            }


        //SI NO HAY NADA DENTRO DE LA LISTA
        if(!busquedaV(nombreV)){

            if(valorV.equals("nulo")){
                nombreVariable.add(nombreV);
                nombreV="";
                tipoDato.add(tipoD);
                tipoD="";
                valorAlmacenado.add(valorV);
            }


            else{

            int band = 0;
                switch(tipoD){

                case "entero":
                        if(isNumeric(valorV)){
                                nombreVariable.add(nombreV);
                                nombreV="";
                                tipoDato.add(tipoD);
                                tipoD="";
                                valorAlmacenado.add(valorV);
                                valorV="nulo";
                                band=1;
                              }
                          break;

                case "flotante":
                        if(isFloat(valorV)){
                                nombreVariable.add(nombreV);
                                nombreV="";
                                tipoDato.add(tipoD);
                                tipoD="";
                                valorAlmacenado.add(valorV);
                                valorV="nulo";
                                band=1;
                              }
                          break;

                case "cadena":

                    if(valorV.charAt(0)=='\u005c"'){

                    nombreVariable.add(nombreV);
                    nombreV="";
                    tipoDato.add(tipoD);
                    tipoD="";
                    valorAlmacenado.add(valorV);
                    valorV="nulo";
                    band=1;

                    }
                    break;

                case "caracter":

                    if(valorV.charAt(0)=='\u005c''){

                    nombreVariable.add(nombreV);
                    nombreV="";
                    tipoDato.add(tipoD);
                    tipoD="";
                    valorAlmacenado.add(valorV);
                    valorV="nulo";
                    band=1;

                    }
                    break;

                 case "bool":

                    if(valorV.equals("verdadero")||valorV.equals("falso")){

                    nombreVariable.add(nombreV);
                    nombreV="";
                    tipoDato.add(tipoD);
                    tipoD="";
                    valorAlmacenado.add(valorV);
                    valorV="nulo";
                    band=1;

                    }
                    break;



            }

            if(band==0){

                String errorS = "Error Semantico en la linea " + token.beginLine + " el tipo de dato y el valor no coinciden";
                erroresSemanticos.add(errorS);
                errorS="";
                nombreV="";
                tipoD="";
                valorV="nulo";

            }


        }

    }


    else{

    String errorS = "Error Semantico en la linea " + token.beginLine + " la variable ya ha sido definida previamente";
                erroresSemanticos.add(errorS);
                errorS="";

        }
  }

  static public void asignar() throws ParseException {//VERIFICAMOS QUE LA VARIABLE YA FUE DEFINIDA

        if(busquedaV(nombreV)){

        //OBTENEMOS SU Ã?NDICE Y SU TIPO DE DATO

        int indice = nombreVariable.indexOf(nombreV);
        tipoD = tipoDato.get(indice);

        //SI LO QUE SE VA A ASIGNAR ES OTRA VARIABLE

            if(ident){
            ident = false;

                //BUSCAMOS SI LA VARIABLE YA FUE DEFINIDA

                if(busquedaV(valorV)){
                    //SI LA ENCONTRO Y PROCEDEMOS A VERIFICAR QUE SEAN DEL MISMO TIPO

                       int indiceV  = nombreVariable.indexOf(valorV);


                       if(tipoDato.get(indiceV).equals(tipoD)){
                            //VERIFICA QUE LA VARIABLE ESTE INICIALIZADA


                                if(!valorAlmacenado.get(indiceV).equals("nulo")){

                                //METEMOS EL VALOR A LA VARIABLE CORRESPONDIENTE

                                    valorV = valorAlmacenado.get(indiceV);
                                }

                                else{

                                //NO SE HA INICIALIZADO LA VARIABLE

                                    String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no se ha inicializado";
                                    erroresSemanticos.add(errorS);
                                    errorS="";
                                    nombreV="";
                                    tipoD="";
                                    valorV="nulo";
                                    return;

                                }


                        }

                        //NO SON DEL MISMO TIPO
                        else{
                          String errorS = "Error Semantico en la linea " + token.beginLine + " la variables no son del mismo tipo";
                          erroresSemanticos.add(errorS);
                          errorS="";
                          nombreV="";
                          tipoD="";
                          valorV="nulo";
                          return;
                          }


                    }

                //EN CASO DE QUE LA VARIABLE NO SE HA DEFINIDO
                else{

                String errorS = "Error Semantico en la linea " + token.beginLine + " la variable que se busca asignar no ha sido definida";
                erroresSemanticos.add(errorS);
                errorS="";
                nombreV="";
                tipoD="";
                valorV="nulo";
                return;
                }

            }





        }

        else{

            String errorS = "Error Semantico en la linea " + token.beginLine + " la variable no ha sido definida";
            erroresSemanticos.add(errorS);
            errorS="";
            return;
        }

                int band = 0;
                switch(tipoD){

                case "entero":
                        if(isNumeric(valorV)){
                                nombreVariable.add(nombreV);
                                nombreV="";
                                tipoDato.add(tipoD);
                                tipoD="";
                                valorAlmacenado.add(valorV);
                                valorV="nulo";
                                band=1;
                              }
                          break;

                case "flotante":
                        if(isFloat(valorV)){
                                nombreVariable.add(nombreV);
                                nombreV="";
                                tipoDato.add(tipoD);
                                tipoD="";
                                valorAlmacenado.add(valorV);
                                valorV="nulo";
                                band=1;
                              }
                          break;

                case "cadena":

                    if(valorV.charAt(0)=='\u005c"'){

                    nombreVariable.add(nombreV);
                    nombreV="";
                    tipoDato.add(tipoD);
                    tipoD="";
                    valorAlmacenado.add(valorV);
                    valorV="nulo";
                    band=1;

                    }
                    break;

                case "caracter":

                    if(valorV.charAt(0)=='\u005c''){

                    nombreVariable.add(nombreV);
                    nombreV="";
                    tipoDato.add(tipoD);
                    tipoD="";
                    valorAlmacenado.add(valorV);
                    valorV="nulo";
                    band=1;

                    }
                    break;

                 case "bool":

                    if(valorV.equals("verdadero")||valorV.equals("falso")){

                    nombreVariable.add(nombreV);
                    nombreV="";
                    tipoDato.add(tipoD);
                    tipoD="";
                    valorAlmacenado.add(valorV);
                    valorV="nulo";
                    band=1;

                    }
                    break;



            }

            if(band==0){

                String errorS = "Error Semantico en la linea " + token.beginLine + " el tipo de dato y el valor no coinciden";
                erroresSemanticos.add(errorS);
                errorS="";
                nombreV="";
                tipoD="";
                valorV="nulo";

            }
  }

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_3R_12()
 {
    if (jj_scan_token(ELSE)) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_12()) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_15()
 {
    if (jj_scan_token(PARI)) return true;
    return false;
  }

  static private boolean jj_3R_14()
 {
    if (jj_scan_token(LLAVEI)) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_13()
 {
    if (jj_scan_token(IF)) return true;
    return false;
  }

  static private boolean jj_3R_11()
 {
    if (jj_scan_token(FOR)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_12()) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public GramaticaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[30];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x7fdc0000,0x6a140000,0x15480000,0x0,0x0,0x0,0x40,0x0,0x0,0xf80,0xf80,0x0,0x1f040,0x60000000,0x180,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7fdc0000,0x7fdc0000,0x7fdc0000,0x0,0x0,0x180,0x7fdc0000,0x7fdc0000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x10000000,0x10000000,0x0,0xf838000,0x7c0000,0xf838000,0x8,0x7c0000,0x3800000,0x0,0x0,0x3800000,0x0,0x0,0x0,0xf838000,0xf800000,0xf801000,0x6fc0,0x6fc0,0xf800000,0xf801000,0x10000000,0x10000000,0x10000000,0xfc0,0x1800000,0x0,0x10000000,0x10000000,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[3];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[61];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 30; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 61; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
