/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGUAL = 6;
  /** RegularExpression Id. */
  int MAS = 7;
  /** RegularExpression Id. */
  int MENOS = 8;
  /** RegularExpression Id. */
  int MULTIPLICAR = 9;
  /** RegularExpression Id. */
  int DIVIDIR = 10;
  /** RegularExpression Id. */
  int MODULO = 11;
  /** RegularExpression Id. */
  int SUMAIGUAL = 12;
  /** RegularExpression Id. */
  int RESTAIGUAL = 13;
  /** RegularExpression Id. */
  int MULTIGUAL = 14;
  /** RegularExpression Id. */
  int DIVIDIRIGUAL = 15;
  /** RegularExpression Id. */
  int MODULOIGUAL = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int WRITE = 18;
  /** RegularExpression Id. */
  int READ = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int BREAK = 22;
  /** RegularExpression Id. */
  int FOR = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int ASIGN = 25;
  /** RegularExpression Id. */
  int ASIGN_A = 26;
  /** RegularExpression Id. */
  int DECLARATE = 27;
  /** RegularExpression Id. */
  int DECLARATE_A = 28;
  /** RegularExpression Id. */
  int ICR = 29;
  /** RegularExpression Id. */
  int DCR = 30;
  /** RegularExpression Id. */
  int PARI = 31;
  /** RegularExpression Id. */
  int PARD = 32;
  /** RegularExpression Id. */
  int LLAVEI = 33;
  /** RegularExpression Id. */
  int LLAVED = 34;
  /** RegularExpression Id. */
  int DELIMITER = 35;
  /** RegularExpression Id. */
  int COMA = 36;
  /** RegularExpression Id. */
  int COMILLA = 37;
  /** RegularExpression Id. */
  int COMENTARIO = 38;
  /** RegularExpression Id. */
  int IGUALDAD = 39;
  /** RegularExpression Id. */
  int MAYOR = 40;
  /** RegularExpression Id. */
  int MAYORI = 41;
  /** RegularExpression Id. */
  int MENOR = 42;
  /** RegularExpression Id. */
  int MENORI = 43;
  /** RegularExpression Id. */
  int DIFERENCIA = 44;
  /** RegularExpression Id. */
  int NEGACION = 45;
  /** RegularExpression Id. */
  int AND = 46;
  /** RegularExpression Id. */
  int OR = 47;
  /** RegularExpression Id. */
  int TRUE = 48;
  /** RegularExpression Id. */
  int FALSE = 49;
  /** RegularExpression Id. */
  int NULL = 50;
  /** RegularExpression Id. */
  int INT = 51;
  /** RegularExpression Id. */
  int FLOAT = 52;
  /** RegularExpression Id. */
  int STRING = 53;
  /** RegularExpression Id. */
  int BOOL = 54;
  /** RegularExpression Id. */
  int CARACTER = 55;
  /** RegularExpression Id. */
  int NUMERO = 56;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 57;
  /** RegularExpression Id. */
  int DECIMAL = 58;
  /** RegularExpression Id. */
  int CADENA = 59;
  /** RegularExpression Id. */
  int CHAR = 60;
  /** RegularExpression Id. */
  int ERRORES = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"principal\"",
    "\"imprimir\"",
    "\"leer\"",
    "\"cuando\"",
    "\"sino\"",
    "\"romper\"",
    "\"ciclo_for\"",
    "\"ciclo_mientras\"",
    "\"asignacion\"",
    "\"asignacion_a\"",
    "\"declarar\"",
    "\"declarar_a\"",
    "\"icr\"",
    "\"dcr\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"\\\"\"",
    "\"#\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"nulo\"",
    "\"entero\"",
    "\"flotante\"",
    "\"cadena\"",
    "\"bool\"",
    "\"caracter\"",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "<DECIMAL>",
    "<CADENA>",
    "<CHAR>",
    "<ERRORES>",
  };

}
